name: Build, test, & publish

on:
  workflow_call:
    inputs:
      should-package:
        type: boolean
        description: Whether to package project and upload as artifact.
        default: false

jobs:
  build-test-publish:
    name: build-test-publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 📦 setup .NET
        uses: actions/setup-dotnet@v3

      - name: ⚙️ restore workloads
        run: dotnet workload restore src/MatomoProvider.sln

      - name: 📦 restore packages
        run: dotnet restore src/MatomoProvider.sln

      - name: 👷 build project
        run: dotnet build --configuration Release --no-restore src/MatomoProvider.sln
    
      - name: ✅ test project
        run: dotnet test --configuration Release --no-build --verbosity normal src/MatomoProvider.sln
  
      - name: 📦 package the application
        if: inputs.should-package
        run: dotnet pack src/MatomoProvider/MatomoProvider.csproj --configuration Release --no-build --output .

      - name: 🔃 upload artifacts
        if: inputs.should-package
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          if-no-files-found: error
          retention-days: 1
          path: ./*.nupkg
